twitter/ccommon

- test-coverage.sh
- test/array/CMakeLists.txt
- test/bstring/CMakeLists.txt
- test/channel/pipe/CMakeLists.txt
- test/channel/tcp/CMakeLists.txt
- test/event/CMakeLists.txt
- test/log/CMakeLists.txt
- test/metric/CMakeLists.txt
- test/option/CMakeLists.txt
- test/pool/CMakeLists.txt
- test/rbuf/CMakeLists.txt
- test/ring_array/CMakeLists.txt
- test/time/timer/CMakeLists.txt
- test/time/wheel/CMakeLists.txt
* fixed test linkage for ubuntu, tested on 14.04.
* while adding libs, added by preferring to add to the front, so dependencies are flushed out, ie m needing to be at the rear.
* an alternative approach would be to have a common set of libs for all tests, but preferred to add explicit dependencies per test suite.
* added support for test-coverage.sh to use xdg-open rather than open when present, ie on ubuntu.
> fixed test linkage for ubuntu

- CMakeLists.txt
- src/CMakeLists.txt
The current install instruction doesn't quite work (includes not installed).
It is also problematic when used as part of pelikan- we want `make install` to just install the server binaries, but currently it will try to install the library as well.
So we are removing the install instructions for now and investigate later.
Also setting a variable for RPATH on OSX to rid warning.
> remove install instructions; get rid of cmake warning

- src/cc_debug.c
> suppress unused parameter warning in debug_log_flush

- src/CMakeLists.txt
fix for Issue #125
- fixed and re-added cmake install instructions, w/ following notes:
- include directory made proper relative
- opened pattern match b/c include directory should only contain files meant for inclusion.
Manually tested by verifying the contents of /usr/local/include/ccommon-1.0/ match those of the project, including include subdirectories.
> Fixed cmake install instructions

- include/time/cc_timer.h
- src/time/cc_timer_darwin.c
- src/time/cc_timer_linux.c
- test/time/timer/check_timer.c
the `duration_snapshot` API allows caller to get a current reading of a started duration `d` and store it into `s`, while leaving `d` still running.
> adding a new API to duration timer

- .travis.yml
- ci/before-install.sh
- ci/run.sh
Add one job in the travis-ci test matrix to test that the rust code builds, links, and tests correctly.
HAVE_RUST is sill defaulted to "off".
> a single job in the travis-ci matrix for building with rust enabled

- include/cc_ring_array.h
- src/cc_ring_array.c
- test/ring_array/check_ring_array.c
Exposing these APIs because they are useful for some twemcache use cases.
- add full, empty, and flush API to ring array
- update ring_array_destroy to take a pointer to the array pointer, so the array pointer can be set to NULL
Will update pelikan with the new destroy api after.
> Additional ring_array API

- docs/modules/cc_ring_array.rst
- include/cc_ring_array.h
- src/cc_ring_array.c
- test/ring_array/check_ring_array.c
Problem
The ring_array doc hasn't been updated with the new API. There is no unit testing for the producer/consumer multi threaded model that ring_array is designed for.
Solution
I have updated the doc describing the new API. I have added a producer/consumer unit test and ensured that it passes. I updated the ring_array example in the doc to show a producer/consumer thread model.
> update ring_array docs for new API, add multi threaded unit test

- test/ring_array/check_ring_array.c
Problem
Forgot to remove an include that is no longer used in check_ring_array.
Solution
Removed the unused header.
> forgot to remove unused include

- ci/install-check.sh
- ci/local-run.sh
- include/cc_log.h
- include/rust/cc_log_rs.h
- include/rust/cc_util_rs.h
- rust/Cargo.lock
- rust/cc_binding/build.rs
- rust/ccommon_rs/Cargo.toml
- rust/ccommon_rs/src/bstring.rs
- rust/ccommon_rs/src/lib.rs
- rust/ccommon_rs/src/log/mod.rs
- rust/ccommon_rs/src/ptrs.rs
- rust/ccommon_rs/src/util.rs
- src/cc_log.c
- test/log/CMakeLists.txt
- test/log/check_log.c
Problem
Rust code should be able to log to ccommon's logging facility to reduce the complexity of configuring embedded features.
Solution
This PR contains code that allows rust to create per-thread `logger` instances for use with the standard `log` crate. This gives us lock-free logging on the rust side, and allows the use of any library without needing to be concerned that that library or its dependencies will log from other threads besides the calling thread. This is a fair tradeoff between speed, safety, and ease of use.
Result
Users will configure the rust logging extension `cc_log_rs` with a directory and a filename prefix. The extension will create new, unique log files under that directory based on that filename prefix per thread on first use.
> Per thread logging

- CMakeLists.txt
- config.h.in
- include/cc_define.h
- src/channel/cc_tcp.c
Problem
We are not using `accept4()` even when it is available to us. By using `accept4()` we can avoid having an additional call to `fcntl()` to set non blocking with each accept.
Solution
This change uses `accept4()` with nonblock flag when it is available.
> use accept4 for tcp_accept when available

- rust/.gitignore
- rust/CMakeLists.txt
- rust/scripts/setup.sh
Problem
IntelliJ (and ostensibly other IDEs) build the rust portion of ccommon as a "cargo project" in `rust/`, which means it will create `rust/target` and output there. When cmake runs in the tld, it will re-compile all the rust targets in `_build/`. One can use an env var of `CARGO_TARGET_DIR` to control this, but that doesn't help because there's no easy way to set that variable automatically inside IntelliJ (and potentially in other IDEs). 
Solution
Cargo will look at `.cargo/config` in each directory in a project for configuration. We run a small script from cmake that writes this file out and sets the target dir to the same one that cmake uses.
Result
We no longer compile the same thing twice to two different locations.
> create a .cargo/config so intellij uses the same target dir as cmake

- include/buffer/cc_buf.h
- include/buffer/cc_dbuf.h
- src/buffer/cc_buf.c
- src/buffer/cc_dbuf.c
- test/CMakeLists.txt
- test/buffer/CMakeLists.txt
- test/buffer/check_buf.c
- test/rbuf/check_rbuf.c
Problem
buffer modules had no unit tests written. Lack of unit test coverage meant some bugs slipped through. Some of the API design didn't make sense.
Solution
I have added unit tests and fixed the bugs that I caught. I refactored the API to make more sense.
- add unit tests for buf/dbuf
- update api to take const for non mutating function
- improve option/metric descriptions
- fix buf_new_cap miscalculation
- fix dbuf_shrink api to no longer return useless status
- fix memory usage metric on destroy
- refactor size check for dbuf
> Add unit tests for buffer, fix buf/dbuf bugs and refactor

- include/cc_bstring.h
- rust/ccommon_rs/src/log/mod.rs
- src/cc_bstring.c
- test/log/check_log.c
Problem
The macro names in cc_bstring to build bstring from string literals/cstrings are not as clear as we would like them to be.
Solution
I have updated the names of these macros to reflect the names we had agreed on.
> improve cc_bstring string literal and cstring names

- include/cc_event.h
- src/event/cc_epoll.c
Problem
epoll_create() no longer take size hint
Solution
use new API and drop the hint.
Result
No behavioral change.
> epoll_create* ignores size hint in newer kernels, switch to new API

- CMakeLists.txt
- ci/local-run.sh
Problem
Build was failing
Solution
Reorder dependencies in top-level CMakeLists.txt, also don't do `make -j` in the ci script.
Result
The build will run
> Reorder dependency includes in cmake, don't parallel build

- rust/Cargo.toml
- rust/cc_binding/Cargo.toml
- rust/ccommon_rs/Cargo.toml
Problem
Rust build is too naively customized, causing the build to fail when integrated into pelikan
Solution
Use only `lib` and `staticlib` outputs, and use the defaults for `LTO` and `rpath` options.
Result
When integrated into pelikan, the cdb extension builds.
> Simplify rust options, specify fewer output targets

- CMakeLists.txt
- include/cc_mm.h
- src/cc_mm.c
Problem
ccommon changes were made with the latest pmem changes in Pelikan, but those changes were not committed upstream.
Solution
Committing the same changes to the upstream ccommon repo (here).
> backport changes made to ccommon in pelikan

- include/time/cc_timer.h
- src/time/cc_timer_darwin.c
- src/time/cc_timer_linux.c
- add fast (low overhead) duration timers for linux
- add duration compare method
Ref: twitter/pelikan#220
> cc: extend duration module

- CMakeLists.txt
To be consistent with README file, which describe prerequisites as:
"To use cmake, make sure you already have it installed and the version is above **2.8**"
> Update Cmake version

- include/cc_queue.h
- replace hardcoded value with "field" to work as general solution
- fix setting last element *(head)->tqh_last = NULL; sets the first
element to NULL, set last element while traverse whole tailq
Ref: twitter/pelikan#221
Commit: https://github.com/twitter/pelikan/pull/221/commits/095a02720e2415b8ff9bca497798dbbcd4a4209a
> Fix TAILQ_REINIT

- src/time/cc_timer_linux.c
- _gettime takes duration_type as parameter not clockid_t
Fix regression in #192 
Ref: twitter/pelikan#220
> Fix now_ns()

- CMakeLists.txt
- test-coverage.sh
- debug build type to pass O0 flag, other to pass O2 flag
- remove unnecessary flags from COVERAGE like -g (ggdb3 is already passed) -Wall -W
Problem
The intention was to have convenient way to pass O0 flag - useful for debugging during development.
Solution
Add possibility to pass optimization flag via Build type in Cmake
@thinkingfish 
Let me know what you think about this solution - I could provide something similar to pelikan repository
> Add basic support of build type

- src/cc_option.c
- simplify check by usage of isalnum to determine if character is alphanumeric
> cc_option simplify _allowed_in_name

- include/cc_bstring.h
- src/cc_bstring.c
- test/bstring/check_bstring.c
Problem
We need to convert string to integer which is useful for supporting the RESP protocol.
Solution
implement atoi64.
Result
unit tests passed.
> add atoi64 to bstring

- src/channel/cc_tcp.c
Problem
Accept returns upon non-blocking error, which means we may leave read-for-accept/close sockets in the queue.
Solution
continue on all non-blocking errors.
Result
draining the server socket queue properly.
> continue on server socket on non-blocking errors

- src/cc_bstring.c
- use isdigit function instead of manual checking for digits
- fix integer overflow in expression -INT64_MIN ( see https://wandbox.org/nojs/clang-6.0.0/permlink/i1zE4BsgBYaiI78j )
> cc_bstring simplify and fix

- rust/Cargo.toml
- rust/cc_binding/build.rs
- rust/cc_binding/src/lib.rs
- rust/cc_binding/src/metric.rs
- rust/ccommon-derive/Cargo.toml
- rust/ccommon-derive/src/attrs.rs
- rust/ccommon-derive/src/lib.rs
- rust/ccommon_rs/Cargo.toml
- rust/ccommon_rs/src/bstring.rs
- rust/ccommon_rs/src/buf.rs
- rust/ccommon_rs/src/ccbox.rs
- rust/ccommon_rs/src/error.rs
- rust/ccommon_rs/src/lib.rs
- rust/ccommon_rs/src/log/mod.rs
- rust/ccommon_rs/src/metric.rs
- rust/ccommon_rs/src/metric/counter.rs
- rust/ccommon_rs/src/metric/fpn.rs
- rust/ccommon_rs/src/metric/gauge.rs
- rust/ccommon_rs/src/metric/mod.rs
- rust/ccommon_rs/src/option.rs
- rust/ccommon_rs/src/option/boolean.rs
- rust/ccommon_rs/src/option/fpn.rs
- rust/ccommon_rs/src/option/mod.rs
- rust/ccommon_rs/src/option/string.rs
- rust/ccommon_rs/src/option/uint.rs
- rust/ccommon_rs/src/util.rs
- rust/ccommon_rs/tests/derive_metrics.rs
- rust/ccommon_rs/tests/derive_options.rs
This PR continues upon the changes from #216. It adds complete bindings for metrics and options as well as a box type wrapping `cc_alloc` and `cc_free`.
Here are all the changes
- Update to edition 2018 for macro hygiene reasons
- Implement CCBox
- Wrap the `metric` struct in different types for each type of metric
- Add a `Metrics` trait and a derive macro for this trait
- Wrap the `option` struct in different types for each type of option
- Add a `Options` trait and a derive macro for this trait
- Implement `Metrics` and `Options` manually for all types they apply for in `cc_bindings`
> Expand rust bindings to add options, metrics, and ccbox

- test/log/check_log.c
This originally tested code that was removed in #218 but was missed because the rust parts of the test are never built even when `-DHAVE_RUST=1` is specified in the cmake configuration.
> Remove test for removed rust logging functionality

- rust/ccommon_rs/Cargo.toml
- rust/ccommon_rs/build.rs
- rust/ccommon_rs/src/error.rs
Problem
`std::any::type_name` is used for better error messages. However, it was only introduced in rust 1.38 while it would be useful to have ccommon useable under rust 1.37.
Solution
This PR uses autocfg to check the rustc version and conditionally switch between the implementations when supported.
> Conditionally use std::any::type_name if it's supported

- ci/run.sh
- limit grep log_test only for ccommon
Intention is to avoid messages in travis log not related with ccommon:
> ./_build/check/share/info/check.info:     check_money.c:9:F:Core:test_money_create:0: Assertion 'money_amount (m)==5' failed:
> ./_build/check/share/info/check.info:     check_money.c:5:E:Core:test_money_create:0: (after this point)
> ./_build/check/share/info/check.info:     ex_log_output.c:14:F:Core:test_fail: Failure
> ./_build/check/share/info/check.info:     ex_log_output.c:18:E:Core:test_exit: (after this point) Early exit
E.g.: https://travis-ci.org/twitter/ccommon/jobs/584280440
> Fix failed test detection

- CMakeLists.txt
- cmake/CMakeCargo.cmake
- cmake/CargoTest.cmake
- rust/ccommon_rs/src/buf.rs
- rust/ccommon_rs/src/log/shim.rs
- rust/ccommon_rs/src/option/string.rs
Problem
Two things
- There are a couple of small bugs/papercuts in the ccommon bindings APIs
- Changes to pure-rust dependencies don't cause rebuilds of rust targets
Solution
Fixed the bugs/papercuts:
- Add some conversion methods to `option::Str` to allow accessing the value as a `CStr` or a `str`
- Add methods to `Buf` to get at the internal `buf` pointer.
Modified `CMakeCargo.cmake` to take into account dependencies
- This works by generating a stamp file whenever a source file is modified, this stamp file is used as a linker dependency which forces cmake to rerun the link step whenever the source code of that crate changes.
- This doesn't work entirely on cmake version < 3.13 (when `INTERFACE_LINK_DEPENDENCY` was introduced). Instead of bumping the required cmake version, incremental …
> Various small bugfixes and usability improvements for rust code

- rust/cc_binding/build.rs
Problem
cc_binding fails to build with certain gcc versions because bindgen misses some typedefs while generating bindings.
Solution
Make bindgen recursively generate the needed bindings from the initial whitelist.
> Make cc_binding generate bindings recursively

- rust/ccommon_rs/src/metric/mod.rs
Problem
C metrics that are manually wrapped in ccommon_rs put the description in the name field instead of the actual name of the metric.
Solution
Use the actual name of the metric.
> Use name of field instead of description for C metrics

- test/channel/pipe/check_pipe.c
Problem
check_pipe is flaky on travis since occasionally it doesn't sleep for the necessary amount of time. (see #142). This showed up in the build logs of #230.
Solution
Rewrite the sleep loop to use nanosleep so that we can retry with the correct time when interrupted.
Result
Hopefully the tests won't be as flaky.
> Change check_pipe to use nanosleep instead of usleep

- rust/ccommon_rs/src/option/mod.rs
Problem
The option names for manually implemented C options are incorrect.
Solution
See title
> Ensure that manually implemented C options use the correct name

- rust/cc_binding/src/lib.rs
- rust/ccommon-backend/src/option/default.rs
- rust/ccommon-backend/src/option/parse.rs
- rust/ccommon-backend/src/option/print.rs
- rust/ccommon-derive/src/attrs.rs
- rust/ccommon-derive/src/lib.rs
- rust/ccommon_rs/src/bstring.rs
- rust/ccommon_rs/src/buf.rs
- rust/ccommon_rs/src/log/shim.rs
- rust/ccommon_rs/src/option/mod.rs
Problem
We have a bunch of rust code that causes warnings when run through clippy. This usually means that it doesn't follow best practices. It also blocks us from running clippy as a pre-commit check.
Solution
Fix the warnings where possible and silence (and deprecate the methods + provide new equivalent once) when not possible.
> Fix clippy lints in code

- rust/ccommon_rs/Cargo.toml
- rust/ccommon_rs/src/buf.rs
Problem
In order to update to the non-alpha version of tokio it is necessary to update the bytes crate.
Solution
Updated the bytes crate.
> Update to use bytes v5.0

- ci/cargo.sh
Improves the cargo build script by fixing some of the logic around
generating the list of manifests to include in the temporary
workspace virtual manifest.
Previously, if there were extra directories in the rust directory,
the script would assume there were cargo manifests directly within
them.
Changes the find command to look for cargo manifests and include
the parent directory of any manifest file in the virtual manifest.
> improve cargo build script

- rust/CMakeLists.txt
- rust/ccommon-array/CMakeLists.txt
- rust/ccommon-array/Cargo.toml
- rust/ccommon-array/src/lib.rs
- rust/ccommon-buffer/CMakeLists.txt
- rust/ccommon-buffer/Cargo.toml
- rust/ccommon-buffer/src/buf/mod.rs
- rust/ccommon-buffer/src/dbuf/mod.rs
- rust/ccommon-buffer/src/lib.rs
- rust/ccommon-channel/CMakeLists.txt
- rust/ccommon-channel/Cargo.toml
- rust/ccommon-channel/src/lib.rs
- rust/ccommon-log/CMakeLists.txt
- rust/ccommon-log/Cargo.toml
- rust/ccommon-log/src/lib.rs
- rust/ccommon-stats/CMakeLists.txt
- rust/ccommon-stats/Cargo.toml
- rust/ccommon-stats/src/lib.rs
- rust/ccommon-stream/CMakeLists.txt
- rust/ccommon-stream/Cargo.toml
- rust/ccommon-stream/src/lib.rs
- rust/ccommon-time/CMakeLists.txt
- rust/ccommon-time/Cargo.toml
- rust/ccommon-time/src/lib.rs
Adds pure rust libraries which contain config structs for the
various ccommon modules. These will be used from pelikan to express
the configuration of parameters for tcp, socket io, buffers, debug,
etc.
> add new libraries to contain config structs

- rust/ccommon-channel/src/lib.rs
- rust/ccommon-channel/src/pipe/mod.rs
- rust/ccommon-channel/src/tcp/mod.rs
Initial implementation was missing the configuration struct for the
pipe channel type.
Adds the config struct and refactors this crate
> add pipe config to rust ccommon-channel

- include/hash/xxhash.h
- src/cc_debug.c
Problem
Show thread name in debug log messages.
Solution
Use `pthread_getname_np()`
Result
Adding a prefix to each log line showing thread name if set, or program name if not.
> Pthread name
